"""add term status

Revision ID: 63fc07004d91
Revises: 34c50fc766bb
Create Date: 2026-05-13 19:25:01.578882

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "63fc07004d91"
down_revision: str | None = "34c50fc766bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Use server_default so existing rows get "accepted" automatically;
    # the column then keeps its NOT NULL contract going forward.
    with op.batch_alter_table("terms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.String(length=16),
                nullable=False,
                server_default="accepted",
            )
        )
        batch_op.create_index(batch_op.f("ix_terms_status"), ["status"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("terms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_terms_status"))
        batch_op.drop_column("status")

    # ### end Alembic commands ###
